server:
  port: 8090
  servlet:
    context-path: /
spring:
  devtools:
    restart:
      # 设置热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
  profiles:
    active: jdbc
  servlet:
    multipart:
      #单个数据的大小
      max-file-size: 100MB
      #总数据的大小
      max-request-size: 100MB
#  resources:
#    static-locations:
#      - classpath:resources
#      - classpath:static
#      - classpath
